name: ink_date
description: Ink Date Application

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.1.15
  connectivity_plus: ^2.2.1
  dartz: ^0.10.1
  firebase_analytics: ^9.1.7
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  firebase_crashlytics: ^2.7.2
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^13.0.4 
  firebase_storage: ^10.3.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: ^1.12.1
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_class: ^2.1.2+4
  logging: ^1.0.2
  lottie: ^1.3.0
  package_info_plus: ^1.4.0
  permission_handler: ^10.0.0
  provider: ^6.0.2
  table_calendar: ^3.0.5
  timezone: ^0.9.1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.6.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/config/
    - assets/fonts/
    - assets/animations/
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

flutter_intl:
  class_name: AppLocalizations
  enabled: true
  main_locale: es_CO
